services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  dbt:
    build:
      context: ./dbt

    container_name: dbt

    working_dir: /workspace/ecommerce_dbt

    volumes:
      - ./:/workspace
      - ./dbt/profiles:/root/.dbt

    depends_on:
      - mysql

    tty: true
    stdin_open: true

volumes:
  mysql_data: